### ISSUE TITLE
Specify Metal Scale (Solar Abundance) Used in C.1.

### ISSUE THREAD

**Issue by farr** [farr/Aldebaran#12]

**Comment by farr** [comment]
The referee writes 

> The medalist scale of the models is not mentioned in Section C.1. I.e., what solar metallicity and abundance mixture was assumed? Grevesse & Sauval (1998), Asplund et al. (2009)? Please specify. The difference is enough to cause a large effective change in Z/X and hence deduced stellar properties.

Tom, can you clarify?

**Comment by grd349** [comment]
@INPROCEEDINGS{Grevesse93,
  author = {Grevesse, N and Noels, A},
  title = {{La composition chimique du soleil}},
  booktitle = {La formation des \'{e}l\'{e}ments chimiques, AVCP},
  year = {1993},
  editor = {{Hauck B. Paltani S.}, Raboud D},
  pages = {205--257}
}

**Comment by farr** [comment]
Thanks, Guy!  Updated the text, and will close the PR momentarily.
