### ISSUE TITLE
Justify Metallicity Values in Table 2

### ISSUE THREAD

**Issue by farr** [farr/Aldebaran#14]
The referee writes 

> Massarotti et al. are not the only ones who report a low metallicity for Aldebaran, Liu et al. 2017 report [Fe/H]=-0.27. Sharma et al. (2016) claim -0.16. The choice of values in Table~2 should therefore be justified.

**Comment by farr** [comment]
Tom, Guy, any thoughts on this?  We could just add these to the table, but then Tom would have to re-run PARAM with the new inputs.  Is there a way you can see to avoid this?

**Comment by grd349** [comment]
The referee is correct that there is a large scatter in the reported metallicity results for Alden. The focus of this work is the new analysis of historical RV data and how this allows new inference. The treatment this scatter of, or at least justification of the selected metallicity is beyond the scope of this work. In the text we already indicate that there is a large scatter and hence we select a number of metallicity values. While we agree there is little science behind this selection we argue that it is still broadly representative and should allow readers to easily interpret the impact of metallicity.

**Comment by grd349** [comment]
How about that?

**Comment by grd349** [comment]
Also, really someone should reanalyse the spectroscopic data using the new log g we have from seismology. I could probably get that done by someone on short order but the metallicity people quote will still be dodgy - they just are 🤐

**Comment by farr** [comment]
Added to ref report.  Closing.
