### ISSUE TITLE
Figure 6 Needed in PNG/EPS Format

### ISSUE THREAD

**Issue by farr** [farr/Aldebaran#17]
Ben, ApJL cannot take PNG files for their typesetting.  Can you re-generate Figure 6 in PDF or (less preferred) EPS format?

**Comment by benjaminpope** [comment]
Turns out I've done something to bork my install of isochrones and it might be complicated to fix - fortunately the png is very high resolution and I've converted this to PDF and committed it. Is this satisfactory or shall I dig around to regenerate it from scratch?

**Comment by farr** [comment]
Ugh.  I'll ask them, but I suspect they are going to choke on anything that
is not vectorized fonts for the labels, axes, etc.  I'll let you know; in
the meantime, as you have time, can you try to sort out your isochrones
install?

**Comment by farr** [comment]
I checked, and they are happy with this, so I'm marking this issue closed.  Good luck updating your isochrones at some point, Ben!
