### ISSUE TITLE
Discuss Issues Around Scaling

### ISSUE THREAD

**Issue by farr** [farr/Aldebaran#9]
The referee writes 

> Discussion of the scaling relations: Given that there is work that shows that there might be a mean-molecular weight term in the numax scaling relation, a discussion of that and the reference to the paper to be given. This is relevant both after Eq. 3 and Eq. C7.

**Comment by farr** [comment]
Hi Dan (I know it's been a while---I'm just getting back on my feet after moving to the US).  Can you add a reference to the work the referee is talking about after Eq. 3 and C7 and any necessary discussion?

**Comment by danxhuber** [comment]
Done. I didn't add a whole lot of new discussion since it's a small effect and we couldn't add a correction even if we wanted to, but I think the revised text should satisfy the referee.

**Comment by farr** [comment]
Great---thanks very much, Dan!

Will
